jobs:
  build:
    name: JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout...
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK...
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build and test...
      run: mvn clean verify
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 21
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout...
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Export Maven coordinates...
      uses: bootique-tools/export-maven-coordinates-action@v1
    - continue-on-error: true
      if: contains(env.POM_VERSION, '-SNAPSHOT')
      name: Set up JDK...
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      if: contains(env.POM_VERSION, '-SNAPSHOT')
      name: Deploy...
      run: mvn clean source:jar-no-fork javadoc:jar deploy -DskipTests --settings
        .github/workflows/maven_settings.xml
name: build test deploy
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
